### ISSUE TITLE
request is mistaken for angular's http function

### ISSUE THREAD

**Issue by justincy** [rootsdev/familysearch-javascript-sdk#89]
Reported here: https://groups.google.com/a/ldsmail.net/d/msg/FSDN/N04eB7JKQXM/BR1wqZ1TYHkJ
Reproduced here: https://github.com/justincy/fs-sdk-node-example
Produces this error:

```
/home/ubuntu/workspace/node_modules/familysearch-javascript-sdk/src/angularjs-wrappers.js:34
    promise.then(
            ^
TypeError: Object #<Request> has no method 'then'
    at Object.exports.httpWrapper (/home/ubuntu/workspace/node_modules/familysearch-javascript-sdk/src/angularjs-wrappers.js:34:13)
    at Plumbing.http (/home/ubuntu/workspace/node_modules/familysearch-javascript-sdk/src/plumbing.js:285:33)
    at Helpers.refPromise.then (/home/ubuntu/workspace/node_modules/familysearch-javascript-sdk/src/helpers.js:105:19)
    at Helpers.nextTick [as _onTimeout] (/home/ubuntu/workspace/node_modules/familysearch-javascript-sdk/src/helpers.js:86:5)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by justincy** [comment]
I was wrong about defer being the problem; it's actually the http function.
